name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: changed_files_spaced
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Debug changed files spaced
        run: |
          echo "All:"
          echo "${{ steps.changed_files_spaced.outputs.all }}"
          echo "Added:"
          echo "${{ steps.changed_files_spaced.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.changed_files_spaced.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.changed_files_spaced.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.changed_files_spaced.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.changed_files_spaced.outputs.added_modified }}"
      - uses: jitterbit/get-changed-files@v1
        id: changed_files_json
        with:
          format: json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug changed files json
        run: |
          echo "${{ steps.changed_files_json.outputs.modified }}" >> modified_files.json
          echo "${{ steps.changed_files_json.outputs.added }}" >> added_files.json
          echo "${{ steps.changed_files_json.outputs.removed }}" >> removed_files.json
          cat removed_files.json
          cat added_files.json
          cat modified_files.json
      - name: Install npm deps
        run: npm install
      - name: Run action
        run: node tech/index.js added_files.json removed_files.json modified_files.json